---
platform: linux

params:
  MDBOOK_RELEASE: 0.2.1

image_resource:
  type: docker-image
  source:
    repository: rustdocker/rust
    tag: stable

inputs:
- name: amethyst

run:
  path: sh
  dir: amethyst
  args:
  - -exc
  - |
    echo "Running latest rustfmt in check mode..."
    export PATH="$HOME/.cargo/bin:$PATH"
    rustup component add rustfmt-preview
    cargo fmt --all -- --check
